### PR TITLE
Use API to get the active spreadsheet id

### PR DESCRIPTION
**Pull request by baerrach**

### CODE REVIEW

**Comment by peterherrmann** [comment]
Hey @baerrach, thanks for the suggestion but the spreadsheet id (optKey parameter) is optional so you can just call BetterLog.useSpreadsheet() with no parameters and it uses the active spreadsheet. See the inline jsdoc: 

```
/**
* Allows logging to a Google spreadsheet.
*
* @param  {String} optKey    The spreadsheet key (optional). Defaults to the active spreadsheet if available.
* @param  {String} optSheetName The name of the sheet (optional). Defaults to "Log". The sheet is created if needed.
* @returns {BetterLog} this object, for chaining
*/
function useSpreadsheet(optKey, optSheetName) {...
```

**Comment by baerrach** [comment]
Ahh, I never looked into the apis provided, I just went straight off the examples in the README.

Would it make sense to update the README to use the no arg version?

**Comment by peterherrmann** [comment]
> Would it make sense to update the README to use the no arg version?

Initially I thought not, since my experience is that I mostly write standalone scripts rather than container bound scripts in Sheets. I'm happy to consider it though. What is some more rationale for using the simple example as you suggest?

**Comment by baerrach** [comment]
I am working on a bound sheet, so cutting and pasting a hard coded string seems wrong.

If there was more than one example that explained when you would use the different versions, that would be fine too. I just wanted to get your code working, I didn't want to think about it too hard or look into source code. So its all cut-n-paste :) 

But when I went to work on the second sheet I had to do more work than I wanted, i.e. paste the spreadsheet id in.

And I have not yet worked out how to do Google Apps, so my instructions for other people to use my work is to copy my example spreadsheet. Obviously, with a hard coded spreadsheet id in the Logger constructor that wont work.

**Pull request closed without merging**
